---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use latest available version
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=512']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4  # Use the latest release of shfmt
    hooks:
      - id: shfmt
        args: [-i, '2', -w]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # Spellcheck uses version 0.9.0 installed locally
    hooks:
      - id: shellcheck
        args: [--enable, all, -x]
      - id: git-check
      - id: git-dirty
      - id: script-must-have-extension
        types: [shell, non-executable]
      - id: script-must-not-have-extension
        types: [shell, executable]
      - id: forbid-binary
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    - id: check-json5
